#!/usr/bin/env bash

# Update package list and upgrade existing packages
sudo apt-get update
sudo apt-get -y upgrade

# Install nginx web server
sudo apt-get -y install nginx

# Configure nginx to listen on port 80
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Restart nginx web server
sudo service nginx restart

# Test if nginx is working properly
if curl -s localhost | grep -q "Hello World!"; then
    echo "Nginx installation completed successfully."
else
    echo "Something went wrong. Please check nginx logs in /var/log/ for more information."
fi
